### ISSUE TITLE
Launching serverless-offline fails with serverless-webpack@2.2.0

### ISSUE THREAD

**Issue by haines** [elastic-coders/serverless-webpack#174]
# This is a Bug Report

## Description

Using config based on the [example](https://github.com/elastic-coders/serverless-webpack/tree/master/examples/serverless-offline), after upgrading to serverless-webpack@2.2.0, serverless-offline fails to start with the following error:

```
Serverless Error ---------------------------------------

  No matching handler found for 'handler'. Check your service definition.
```

The same config works fine with serverless-webpack@2.1.0.

Minimal(ish) repro: https://github.com/haines/serverless-webpack-issue

## Additional Data

* ***Serverless-Webpack Version you're using***: 2.2.0
* ***Webpack version you're using***: 3.4.1
* ***Serverless Framework Version you're using***: 1.18.0
* ***Operating System***: Mac OS X 10.12.5
* ***Stack Trace (if available)***: N/A

**Comment by HyperBrain** [comment]
I fixed the example. The handler definition must include the path so that the Serverless framework and the plugin knows the location of the handler.

```
functions:
  first:
    handler: src/handler.hello
```

**Comment by HyperBrain** [comment]
I will check the other examples too.

**Comment by HyperBrain** [comment]
It is important that the handler points to the correct directory. Other plugins also might need the location and will fail if you do not set it - this is the same behavior as with Serverless without the plugin.

**Comment by haines** [comment]
Thanks for the quick response! I've updated the config as suggested, and it starts up ok, but now I get an error when I hit the endpoint:

```
Serverless: Error while loading hello
[ 'Error: Cannot find module \'/Users/haines/work/serverless-webpack-issue/.webpack/src/handler\'',
  'at Function.Module._resolveFilename (module.js:469:15)',
  'at Function.Module._load (module.js:417:25)',
  'at Module.require (module.js:497:17)',
  'at require (internal/module.js:20:19)',
  'at Object.createHandler (/Users/haines/work/serverless-webpack-issue/node_modules/serverless-offline/src/functionHelper.js:35:21)',
  'at handler (/Users/haines/work/serverless-webpack-issue/node_modules/serverless-offline/src/index.js:480:40)',
```

**Comment by HyperBrain** [comment]
you have to use `--location .webpack` with the offline plugin.

**Comment by HyperBrain** [comment]
This is how we invoke offline in our projects:
`node ./node_modules/serverless/bin/serverless offline --location .webpack --noTimeout --dontPrintOutput`

**Comment by haines** [comment]
I took it out because it seems to make things worse, with `--location .webpack` the error is 

```
Cannot find module  '/Users/haines/work/serverless-webpack-issue/.webpack/.webpack/src/handler'
```

note the `.webpack/.webpack/src`. Without `--location` it tries to load `.webpack/src/handler`. I'm assuming it should be loading `.webpack/handler`?

**Comment by HyperBrain** [comment]
can you try the lib.entries variant I mentioned above, or use "src/handler.js" as filename?

**Comment by haines** [comment]
Nice, it's working with `lib.entries`, which has made it bundle to `.webpack/src/handler.js` instead of `.webpack/handler.js`, and it loads correctly.

Adding `--location .webpack` still causes it to fail trying to load `.webpack/.webpack`. Omitting `--location` works though, so we'll roll with that!

Thanks for your help.

**Comment by HyperBrain** [comment]
👍

**Comment by ringods** [comment]
@HyperBrain I'm bitten by this bug too and I followed your advice to use `entry: slsw.lib.entries`, but I get this error when running Webpack:
```
$ node_modules/.bin/webpack
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   The entry point(s) of the compilation.
   Details:
    * configuration.entry should NOT have less than 1 properties ({
        "keyword": "minProperties",
        "dataPath": ".entry",
        "schemaPath": "#/oneOf/0/minProperties",
        "params": {
          "limit": 1
        },
        "message": "should NOT have less than 1 properties",
        "schema": 1,
        "parentSchema": {
          "minProperties": 1,
          "additionalProperties": {
            "oneOf": [
              {
                "description": "The string is resolved to a module which is loaded upon startup.",
                "minLength": 1,
                "type": "string"
              },
              {
                "description": "All modules are loaded upon startup. The last one is exported.",
                "$ref": "#/definitions/common.nonEmptyArrayOfUniqueStringValues"
              }
            ]
          },
          "description": "Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.",
          "type": "object"
        },
        "data": {}
      }).
      object { <key>: non-empty string | [non-empty string] }
      Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
    * configuration.entry should be a string.
    * configuration.entry should be an array:
      [non-empty string]
    * configuration.entry should be an instance of function
      function returning an entry object or a promise..
```

This is my `webpack.config.js`:
```
const path = require('path');
const webpack = require('webpack');
const slsw = require('serverless-webpack');

const config = {
  entry: slsw.lib.entries,
  target: 'node', // Ignores built-in modules like path, fs, etc.

  output: {
    libraryTarget: 'commonjs',
    path: path.resolve(`${__dirname}/.webpack`),
    filename: '[name].js',
  },

  module: {
    rules: [{
        test: /\.elm$/,
        exclude: [/elm-stuff/, /node_modules/],
        use: {
          loader: 'elm-webpack-loader',
          options: {}
        }
      }],
  },
};

module.exports = config;
```

Any idea?

**Comment by HyperBrain** [comment]
@ringods Hi. Thanks for asking 👍 . Can you additionally post the function definition from your `serverless.yml`? The error (webpack config error) points somehow to a handler resolution problem.
What you can do too, is a `console.log(slsw.lib.entries)` in the config, so that we see what is put in there by the plugin. Please let me know of this information.

FYI: I never used the elm-loader (and do not know anyone who uses it ;-) ). But normally it should work with any available webpack loader.

**Comment by HyperBrain** [comment]
@ringods Oh, I just saw that you invoked webpack directly from the commandline. Then the serverless-webpack context will not be set -> that should be the reason for the failure. Using the lib extensions of the plugin needs to have webpack invoked by the Serverless framework.

Can you try to invoke the webpack build with `serverless package` or `serverless webpack`?

**Comment by ringods** [comment]
`serverless.yml`:
```
service: integrations

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    location: .webpack
    dontPrintOutput: true

functions:
  hello:
    handler: .webpack/hello.handler # Refers to function `handler` exported from `Hello/api.js`
    events:
      - http:
          integration: lambda-proxy
          path: /
          method: ANY
```

All of serverless and plugins are devDependencies. I added this npm script:
`"package": "serverless package"`

Here is the output:
```
$ SLS_DEBUG=* npm run package

> rq-business-integrations@0.0.1 package /Users/ringods/Projects/releasequeue/rq-business-integrations
> serverless package

Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook before:deploy:createDeploymentArtifacts
Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook after:deploy:createDeploymentArtifacts
Serverless: Bundling with Webpack...
Time: 33ms

ERROR in Entry module not found: Error: Can't resolve './.webpack/hello.js' in '/Users/ringods/Projects/releasequeue/rq-business-integrations'

  Error --------------------------------------------------

  Webpack compilation error, see above

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Webpack compilation error, see above
    at BbPromise.fromCallback.then.stats (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/serverless-webpack/lib/compile.js:24:17)
    at emitRecords.err (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/webpack/lib/Compiler.js:354:15)
    at /Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/webpack/node_modules/async/dist/async.js:421:16
    at eachOfArrayLike (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/webpack/node_modules/async/dist/async.js:991:9)
    at eachOf (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/webpack/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/webpack/node_modules/async/dist/async.js:3145:5)
    at emitFiles (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/webpack/lib/Compiler.js:319:21)
    at /Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at ServerlessWebpack.compile (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/serverless-webpack/lib/compile.js:14:8)
From previous event:
    at Object.before:deploy:createDeploymentArtifacts [as hook] (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/serverless-webpack/index.js:113:10)
    at BbPromise.reduce (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/serverless/lib/classes/PluginManager.js:236:55)
From previous event:
    at PluginManager.invoke (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/serverless/lib/classes/PluginManager.js:236:22)
    at PluginManager.run (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/serverless/lib/classes/PluginManager.js:255:17)
    at variables.populateService.then (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Serverless.run (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/Users/ringods/Projects/releasequeue/rq-business-integrations/node_modules/serverless/bin/serverless:39:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.1.2
     Serverless Version:     1.19.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rq-business-integrations@0.0.1 package: `serverless package`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rq-business-integrations@0.0.1 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ringods/.npm/cache/_logs/2017-08-15T21_27_18_254Z-debug.log
```

**Comment by HyperBrain** [comment]
Looking at your `serverless.yml`, the handler definition is the issue. It should point to the handler js file, not into the webpack directory. This should be done for all functions. It is important, that Serverless knows the location of the handlers.

Sample:
```
functions:
  forms:
    handler: src/Forms/api.handler     <-- HERE!
```

The handler must reference the export in the actual handler file, not the compiled one. If you change these accordingly it should work.

BTW: You can use `^3.0.0-rc.1` as serverless-webpack version. Then you can try the V3 already ;-)

I will check with your test project later today, but you already can try my suggestion.

**Comment by HyperBrain** [comment]
@ringods If it works with the corrections, would you mind that I put your example project into the official serverless-webpack examples? It would be a great addition to have an elm-loader example there 🙌

**Comment by HyperBrain** [comment]
@ringods I did a PR to the repo (https://github.com/ktonon/elm-serverless-demo/pull/2) which makes it work. It is your decision to keep sls-webpack v3 in or use 2.2.0. Both should work.
