### PR TITLE
V3.0.0

### LINKED ISSUE #108: Getting sourcemaps to work
What is the trick for getting sourcemaps to work correctly with the stacktraces in AWS logs?

I've currently got `require('source-map-support').install();` after all other imports in a file `/src/lambdas/webhook.ts`.

Webpack config looks like this:
```
var path = require('path');

module.exports = {
  entry: {
    '/src/lambdas/webhook': './src/lambdas/webhook.ts',
    '/src/lambdas/queue-poller': './src/lambdas/queue-poller.ts',
    '/src/lambdas/queue-worker': './src/lambdas/queue-worker.ts',
  },
  target: 'node',
  devtool: 'source-map',
  resolve: {
    modules: [
      path.join(__dirname, 'src'),
      path.join(__dirname, 'node_modules')
    ],
    extensions: ['', '.ts', '.js']
  },
  module: {
    loaders: [
      { test: /\.ts(x?)$/, loader: 'ts-loader' }
    ]
  },
  resolve: {
    extensions: ['.ts', '.js'],
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js'
  },
};
```

Here is the contents of the uploaded zip:
```
 ⇒ unzip -l .serverless/trebuchet.zip
Archive:  .serverless/trebuchet.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     3020  02-24-2017 22:37   src/lambdas/queue-poller.js
     3140  02-24-2017 22:37   src/lambdas/queue-poller.js.map
     2956  02-24-2017 22:37   src/lambdas/queue-worker.js
     3073  02-24-2017 22:37   src/lambdas/queue-worker.js.map
  3655773  02-24-2017 22:37   src/lambdas/webhook.js
  5682470  02-24-2017 22:37   src/lambdas/webhook.js.map
---------                     -------
  9350432                     6 files
```
The output for both logged exceptions and unhandled exceptions is still using the full bundle.

Am I missing something from the `source-map-support` config?  

If everything is working correctly should the logged and unhandled exceptions be using the stacktraces from the sourcemap?

### LINKED ISSUE #116: Some modules are missing when using webpack 2
# Problem
We tried to use Webpack 2 and the current master branch of the webpack plugin.
The bundle generation is creating a correct bundle, but the packaged node modules,
that are installed as sibling to the bundle by the plugin are missing some external modules.

I.e. although they are present in the local services' package.json, they do not appear in
the package.json that is temporarily created by the webpack plugin to install the needed
external modules.

This leads to "required module not found" errors, when executing the compiled code on AWS
after Serverless deployed it.

# Root cause
The plugin parses the webpack stats to find external modules by matching the returned stats
with "external ".

See comment below: Webpack 2's dependency optimization sometimes removes first level dependencies but keeps the removed dep's second level dependencies.

### LINKED ISSUE #117: Bundling of node modules works oddly
I use `webpack-node-externals` for bundling mode modules like this:
```
externals: [nodeExternals({
    modulesFromFile: true,
  })],
```
(whole config is here: https://github.com/keboola/developer-portal/blob/master/webpack.config.js)

And it worked quite well until recently when I decided to move the deployment to Docker and noticed that the code stopped working because some modules are missing. I have found out that the `nodeExternals()` method returns list of 47 modules however when I run `serverless deploy`, it bundles 137 modules. Although quite more then I want but the code still works. But the weird thing is that when I run the same deployment from a docker container (using this Dockerfile: https://github.com/keboola/developer-portal/blob/docker-travis/Dockerfile) it bundles only 18 modules, so the code fails on missing modules. Would you have any idea why is this going on? Thanks.

### LINKED ISSUE #120: serverless-webpack is not compatible with new function level individual packaging
I am using serverless 1.11.0 with the new function level individual packaging feature.
Here is a piece of my serverless.yml.

```
request:
   handler: request.handler
   package:
       individually: true
       include:
          - request.js
```

When I `sls deploy`, I get this error.

```
Serverless: Packaging service...

  Error -------------------------------------------------- 

     ENOENT: no such file or directory, open '/Users/deathweasel/Documents/repos/****/****/.webpack/.serverless/service-functionname.zip'****

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------
Error: ENOENT: no such file or directory, open '/Users/deathweasel/Documents/repos/****/****/.webpack/.serverless/service-functionname.zip'****
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at AwsCompileFunctions.compileFunction (/Users/deathweasel/Documents/repos/****/****/node_modules/serverless/lib/plugins/aws/deploy/compile/functions/index.js:176:24)
    at serverless.service.getAllFunctions.forEach (/Users/deathweasel/Documents/repos/****/****/node_modules/serverless/lib/plugins/aws/deploy/compile/functions/index.js:218:39)
    at Array.forEach (native)
    at AwsCompileFunctions.compileFunctions (/Users/deathweasel/Documents/repos/****/****/node_modules/serverless/lib/plugins/aws/deploy/compile/functions/index.js:218:8)
    at BbPromise.reduce (/Users/deathweasel/Documents/repos/****/****/node_modules/serverless/lib/classes/PluginManager.js:210:55)
From previous event:
    at PluginManager.invoke (/Users/deathweasel/Documents/repos/****/****/node_modules/serverless/lib/classes/PluginManager.js:210:22)
    at PluginManager.run (/Users/deathweasel/Documents/repos/****/****/node_modules/serverless/lib/classes/PluginManager.js:225:17)
    at Serverless.run (/Users/deathweasel/Documents/repos/****/****/node_modules/serverless/lib/Serverless.js:97:31)
    at serverless.init.then (/Users/deathweasel/Documents/repos/****/****/node_modules/serverless/bin/serverless:23:50)
```

I did a quick examination of the code and it looks like serverless-webpack doesn't examine that setting at all.

### LINKED ISSUE #151: Integrate with "Serverless invoke local" and change the "webpack invoke" command
# This is a Feature Proposal

## Description

Serverless offers a fully working `local invoke` command that handles all possible
kinds of invocations, sets the function's environment correctly and much more.

There is no need to have a separate `webpack invoke` command that replicates (only)
parts of this functionality and binds resources to maintain it properly.

It would be better to integrate seamlessly with `local invoke` by hooking the important
lifecycle events exposed by the command. Finally, `serverless invoke local` should 
invoke the function after the webpack compile has been triggered as part of the lifecycle
hooks in place.

To make it completely seamless, the `webpack invoke` command should techincally just use Serverless'
pluginManager to spawn the `invoke local` command like this: `this.serverless.pluginManager.spawn('invoke:local')`.

This solution would also make the invocation provider independent as Serverless fully takes care of that already.

Related issue(s):
#128 (arbitrary provider support)

### LINKED ISSUE #152: Remove the serve command
# This is a Feature Task

## Description

In #135 we decided that the `serve` command will be removed because it does
not add additional value to the Serverless framework as the `serverless-offline`
integrates with the plugin and does the job even better.

This task should contain all (technical) discussions about the actual removal, so
that it can be removed without affecting the other commands/features that will stay 
in the plugin.

The target milestone for the removal is version 3.0.0 as it is (by definition) a breaking change
that needs actions to be taken by users that currently use it.

All PRs for the feature have to be targeted to the (new) `v3.0.0-remove-serve` branch to keep master clean
for any 2.x.x bugfix or feature versions. We will use this branch to stabilize the feature. The branch will be
rebased to master each time something is added there.

Similar or dependent issue(s):
* #135

### LINKED ISSUE #173: Use the standard Serverless servicePath in the plugin
# This is a Feature Proposal

## Description

Until now the plugin overwrites the `servicePath` property in Serverless during its lifecycle and
sets it back in the cleanup lifecycle event. This makes the whole system very fragile and dependent on
the consistent use of the property in Serverless as well as all other plugins. In the extreme, we can
throw the dice, if the next Serverless version will lead to problems or not.

This behavior should be changed and the plugin should use the given `servicePath` as plugins are
expected to do.

I think the change is not trivial, because there has to be a reason, why this approach has been taken.
We should analyze every single step in the plugin and check if there are any issues that can arise from
changing it to a stable use.

After the implementation has been done, it should be tested properly and ripen in master for a while.

### LINKED ISSUE #181: V3: Deploying a single function with individual packaging does not work
The whole project deploys correctly, but when deploying individual functions I'm getting the following error:

```
Serverless: Bundling with Webpack...
Time: 6122ms
                                     Asset     Size  Chunks                    Chunk Names
functions/model/job_request/get_details.js  3.84 MB       0  [emitted]  [big]  functions/model/job_request/get_details
Serverless: Packaging function: job-request-get_details...

  Error --------------------------------------------------

  ENOENT: no such file or directory, open '<project-serverless>/.webpack/.serverless/job-request-get_details.zip'
```

### PR DESCRIPTION
**Pull request by HyperBrain**
## What did you implement:

This PR merges the v3.0.0 branch to master as soon as it is stabilized.
Feel free to test this branch - this will help to make sure that it works properly.

As soon as all features have been merged, the V3.0.0 branch will be published as prerelease for testing.

Closes #181
Closes #120
Closes #173
Closes #117
Closes #116
Closes #108 
Relates to #60

Closes #151 
Closes #152 

## Contained PRs

#161 , #153 , #177

### CODE REVIEW

**Comment by cwaltken-edrans** [comment]
Hi Frank,
i just tried out v3.0.0 with my project without success and the following error:
```zsh
{ Error: Cannot find module '/<project_path_redacted>/.webpack/handler'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at AwsInvokeLocal.invokeLocalNodeJs (/usr/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:156:33)
    at AwsInvokeLocal.invokeLocal (/usr/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:114:19)
    at AwsInvokeLocal.tryCatcher (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5) code: 'MODULE_NOT_FOUND'
}
```
My `webpack.conf.js` looks like this:
```js
module.exports = {
  entry: './handler.js',
  target: 'node',
  module: {
    loaders: [{
      test: /\.js$/,
      loaders: ['babel-loader'],
      include: __dirname,
      exclude: /node_modules/,
    },
    {
      test: /\.json$/,
      loader: 'json-loader'
    },
    {
      test: /\.yaml$/,
      loader: "file-loader"
    }]
  },
};
```
Note that the same project works with v2.2.0 and `webpack invoke`.
I tried v3.0.0. because I need the new generalized `invoke local` function.
It seems to me v2.2.0 has a bug if you add static files with the webpack file-loader, since webpack invoke does not have the bundled file in the execution path.

I'm looking forward to v3.0.0!
Regards
Clemens

**Comment by HyperBrain** [comment]
@cwaltken-edrans Hi,

I had the issue just today too, and already fixed it in the `v3.0.0-individual-packaging` branch.
Could you check with that branch and let me know if it is also fixed for you?

**Comment by cwaltken-edrans** [comment]
P.S:: Using automatic entry resolution as described in the docs or exporting the module I get a type error from serverless:

```
  Type Error ---------------------------------------------
 
  lambda is not a function
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.11.1
     Serverless Version:     1.18.0
```

**Comment by HyperBrain** [comment]
That is strange. Can you put a simple sample project somewhere (maybe gist or github) with that the dynamic entry issue is reproducible?

**Comment by HyperBrain** [comment]
@cwaltken-edrans If you encounter something that's not working you can open an issue (just prefix it with **V3:**). Then we can try to solve them individually 😃 .
